spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none #create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#            create-source: metadata

  flyway:
    enabled: true #false
    locations: classpath:db/migration
