spring:
  # H2 Connection
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  # H2 Client
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  # Disable Flyway
  flyway:
    enabled: false
