create table
    tb_categoria (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

create table
    tb_city (
        id bigint generated by default as identity,
        state_id bigint,
        name varchar(255),
        primary key (id)
    );

create table
    tb_cliente (
        client smallint check (client between 0 and 1),
        id bigint generated by default as identity,
        document varchar(255),
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

create table
    tb_endereco (
        city_id bigint,
        client_id bigint,
        id bigint generated by default as identity,
        complement varchar(255),
        neighborhood varchar(255),
        number varchar(255),
        postal_code varchar(255),
        street varchar(255),
        primary key (id)
    );

create table
    tb_item_pedido (
        discount float (53),
        price float (53),
        quantity integer,
        order_id bigint not null,
        product_id bigint not null,
        primary key (order_id, product_id)
    );

create table
    tb_pagamento (
        state smallint check (state between 0 and 2),
        order_id bigint not null,
        primary key (order_id)
    );

create table
    tb_pagamento_boleto (
        due_date timestamp(6),
        order_id bigint not null,
        payment_date timestamp(6),
        primary key (order_id)
    );

create table
    tb_pagamento_cartao (
        plots_number integer,
        order_id bigint not null,
        primary key (order_id)
    );

create table
    tb_pedido (
        address_id bigint,
        client_id bigint,
        id bigint generated by default as identity,
        instant timestamp(6),
        primary key (id)
    );

create table
    tb_produto (
        price float (53),
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

create table
    tb_produto_categoria (
        category_id bigint not null,
        product_id bigint not null,
        primary key (category_id, product_id)
    );

create table
    tb_state (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

create table
    tb_telefone (client_id bigint not null, phones varchar(255));

alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;

alter table if exists tb_endereco add constraint FKmu22g1xuk88rv9hec41ug6akf foreign key (city_id) references tb_city;

alter table if exists tb_endereco add constraint FKtpn2ah8i41mf4dgddcioq852i foreign key (client_id) references tb_cliente;

alter table if exists tb_item_pedido add constraint FK6hga8ai415cq8jjg036ptfudm foreign key (product_id) references tb_produto;

alter table if exists tb_item_pedido add constraint FK54kekgdaxewxu0miigukw408p foreign key (order_id) references tb_pedido;

alter table if exists tb_pagamento add constraint FK7nmbsy62posrtwttjac45j9kt foreign key (order_id) references tb_pedido;

alter table if exists tb_pagamento_boleto add constraint FK115hhuj8ixsfgntld3q6ilgqq foreign key (order_id) references tb_pagamento;

alter table if exists tb_pagamento_cartao add constraint FK23l6hydcqrq1tyhbw3k9a97ld foreign key (order_id) references tb_pagamento;

alter table if exists tb_pedido add constraint FK9rqvgwcrphl6foaljgqdlicgr foreign key (address_id) references tb_endereco;

alter table if exists tb_pedido add constraint FK4jgc6wdyd5qy8eec96xwrjgbr foreign key (client_id) references tb_cliente;

alter table if exists tb_produto_categoria add constraint FKf4p1niejepvegx693b8rkul21 foreign key (category_id) references tb_categoria;

alter table if exists tb_produto_categoria add constraint FKpm35vej3uilfo4s1do2utq7i foreign key (product_id) references tb_produto;

alter table if exists tb_telefone add constraint FKaoqslgw78yr5fp114s44hr7wd foreign key (client_id) references tb_cliente;